---
port: 8080
data_dir: /root/data
blobstore_dir: /root/data/stemcells
credentials:
  user: admin
  password: admin
softlayer:
  user: xxxxx
  key: xxx
redis:
  address: 1.2.3.4
  port: 1234
  password: xxxxxxxx
resque:
 logging:
   file: test.log
   level: INFO